[[actions]]
name = "play"
platform = "windows"
path = "Realgen/Realgen.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "Realgen/Realgen"
args = ["--launched-through-itch"]
